# https://code.visualstudio.com/api/references/extension-manifest
version: 0.0.7
name: custom-app-icons
displayName: &title Custom App Icons
icon: icon.png
galleryBanner:
  color: "#5CADFF"
  theme: dark
description: Easily replace the VS Code app icon, and associated file icons, with your own from the user settings folder.
categories:
- Themes
keywords:
- app icon
- file icons
- dock
- desktop
- start menu

homepage: https://marketplace.visualstudio.com/items?itemName=danielbayley.custom-app-icons
repository:
  url: https://github.com/danielbayley/vscode-custom-app-icons
bugs:
  url: https://github.com/danielbayley/vscode-custom-app-icons/issues
  email: daniel.bayley@me.com
qna: https://github.com/danielbayley/vscode-custom-app-icons/discussions/categories/q-a

author:
  name: Daniel Bayley
  email: daniel.bayley@me.com
  url: https://danielbayley.dev

publisher: danielbayley
license: MIT
sponsor:
  url: https://github.com/sponsors/danielbayley

os:
- darwin
- win32
engines:
  node: ">=14"
  vscode: ^1.0.0

private: true
main: index.js

extensionKind: [ui]
activationEvents: ["*"]

contributes:
  configuration:
    title: *title
    properties:
      customAppIcons.path:
        markdownDescription: |
          Folder path to `*.`[`icns`](https://github.com/microsoft/vscode/tree/main/resources/darwin)
          /[`ico`](https://github.com/microsoft/vscode/tree/main/resources/win32) files.
        scope: machine
        type: string

packageManager: ^pnpm@8.7.1
devDependencies:
  "@babel/core": ^7.22.11
  "@babel/preset-env": ^7.22.14
  "@vscode/vsce": ^2.21.0
  chokidar-cli: ^3.0.0
  coffeescript: ^2.7.0
  esbuild: ^0.19.2
  github-release-cli: ^2.1.0
  ovsx: ^0.5.1
  replace-in-file: ^6.3.5
  svg2png: ^4.1.1
  yamljs: ^0.3.0

dependencies:
  fast-glob: ^3.3.1
  jszip: ^3.10.0
  touch: ^3.1.0

babel:
  presets: ["@babel/env"]

scripts:
  prebuild: pnpm clean
  build: pnpm /^build.+/ && pnpm bundle
  build.icon: svg2png *.svg --width 256
  build.manifest: yaml2json package.y*ml --pretty --save
  build.coffee: coffee --compile --inline-map *.coffee
  bundle: >-
    esbuild $npm_package_main
    --outfile=$npm_package_main --allow-overwrite
    --bundle
    --platform=node
    --external:vscode

  pretest.vscode: yaml2json .vscode --pretty --save

  vscode:prepublish: pnpm build --minify
  version: |
    replace-in-file version:\ $npm_{old,new}_version package.yaml
    [ $RELEASE ] || exit 0
    git commit --all --message $npm_new_version
    git push

  prepackage: pnpm build.manifest
  package: >-
    vsce package
    --allow-star-activation
    --no-dependencies
    --no-git-tag-version
    --out $npm_package_name.vsix

  prerelease: git stash --include-untracked --keep-index
  release: RELEASE=true pnpm package
  postrelease: pnpm /^release.+/
  release.vsce: vsce publish --packagePath *.vsix
  release.ovsx: ovsx publish *.vsix
  release.github: >-
    github-release upload *.vsix
    --owner $npm_package_publisher
    --repo vscode-$npm_package_name
    --tag v$npm_package_version

  watch: pnpm /^watch.+/
  watch.icon: chokidar *.svg --command 'pnpm build.icon'
  watch.manifest: pnpm build.manifest --watch
  watch.coffee: chokidar *.coffee --command 'pnpm build.coffee'
  watch.bundle: pnpm bundle --watch

  clean: rm -f *.{png,js*,vsix}
